# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.On_Off = QtWidgets.QGroupBox(parent=Dialog)
        self.On_Off.setGeometry(QtCore.QRect(30, 50, 241, 81))
        self.On_Off.setObjectName("On_Off")
        self.on = QtWidgets.QRadioButton(parent=self.On_Off)
        self.on.setGeometry(QtCore.QRect(20, 30, 109, 24))
        self.on.setObjectName("on")
        self.off = QtWidgets.QRadioButton(parent=self.On_Off)
        self.off.setGeometry(QtCore.QRect(20, 50, 109, 24))
        self.off.setObjectName("off")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.On_Off.setTitle(_translate("Dialog", "On/Off"))
        self.on.setText(_translate("Dialog", "Supply On"))
        self.off.setText(_translate("Dialog", "Supply Off"))
